name: InfinityDurability
main: amata1219.infinity.durability.InfinityDurability
version: 1.0.0
api-version: 1.13
author: amata1219(Twitter@amata1219)

commands:
  idcheck:
    description: main command.
    usage: /<command>
    permission: infinity.durability.idcheck
    permission-message You do not have permission.